// THIS IS WHERE WE HAVE OUR LAYOUT CONSTRAINS OF OUR COMPONENTS
// ALL THE PAGES WILL BE INJECTED INTO THE CHILDREN PROP WE SE BELLOW

import { SessionProvider } from '../components/SessionProvider'
import { getServerSession } from 'next-auth'
import Sidebar from '../components/Sidebar'
import '../styles/globals.css'
import { authOptions } from '../pages/api/auth/[...nextauth]'
import { Login } from '../components/Login'
import ClientProvider from '../components/ClientProvider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <head />
      <body>
        <SessionProvider session={session}>
          {!session ? ( 
            <Login />
          ) : (
          <div className='flex'>
            {/* Sidebar */}
            <div className='bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]'>
            <Sidebar />
            </div>

            {/* ClientProvider - Notification*/} 
            {/* Even though ´layout.tsx is a server component, we can use a ClientProvider component to implement Client side functionalities  */}
            <ClientProvider />

            <div className='bg-[#343541] flex-1'>{children}</div>
          </div>
          )}
        </SessionProvider>
      </body>
    </html>
  )
}
